### ISSUE TITLE
Error launching web browser

### ISSUE THREAD

**Issue by vvavrychuk** [directhex/monodevelop-flatpak#2]
Running ASP.NET MVC 5.2.3 project I get error related to opening browser

![image](https://cloud.githubusercontent.com/assets/152563/19510445/f354d9d8-95eb-11e6-88c8-653f4fdf79b4.png)

Everything works fine after that so far.

**Comment by egeexyz** [comment]
We've been relying on MonoDevelop 5.x because of this bug. If nothing else, please hide the error so that it doesn't pop up in the developer's face each time they run the solution.

**Comment by directhex** [comment]
This is fixed in current versions.
