### ISSUE TITLE
flatpak installs 7.1 preview instead of 6.1

### ISSUE THREAD

**Issue by katerd** [directhex/monodevelop-flatpak#5]
Executing `flatpak install --user --from https://download.mono-project.com/repo/monodevelop.flatpakref` as per the docs installs the incorrect version - 7.1 preview instead of the stable 6.1 release.

```
dale@asgard:~/Downloads$ flatpak list
Ref                                   Options     
com.xamarin.MonoDevelop/x86_64/stable user,current
org.freedesktop.Sdk/x86_64/1.4        user,runtime
```

**Comment by directhex** [comment]
The website has been hopelessly out of date for a long time, due to no dedicated ownership. 6.1 wasn't current for a LONG time.

Version numbering ought to mirror what's published to the Xamarin releases blog: http://releases.xamarin.com/
